/**
 * Makes @chainsafe/libp2p-quic survive `bun build --compile`.
 *
 * Its loader (dist/src/napi.js, generated by NAPI-RS) picks the native binding at run time with
 * `createRequire(import.meta.url)` and a platform switch. The bundler cannot follow that, so the
 * `.node` file never enters the binary and QUIC fails with "Cannot find native binding" on start.
 * This plugin replaces the loader, at build time, with a static require of the binding for the
 * platform being built -- a static require is what `--compile` embeds.
 */
import type { BunPlugin } from 'bun'

const EXPORTS = ['Client', 'Connection', 'ConnectionStats', 'EndpointStats', 'QuinnConfig', 'Server', 'Stream', 'SocketFamily']

function bindingPackage(): string {
  const { platform, arch } = process
  if (platform === 'linux') {
    // glibc unless the runtime says otherwise; a musl build needs a musl host to build on anyway.
    const glibc = (process.report?.getReport() as any)?.header?.glibcVersionRuntime !== undefined
    return `@chainsafe/libp2p-quic-linux-${arch}-${glibc ? 'gnu' : 'musl'}`
  }
  if (platform === 'darwin') return `@chainsafe/libp2p-quic-darwin-${arch}`
  if (platform === 'win32') return `@chainsafe/libp2p-quic-win32-${arch}-msvc`
  throw new Error(`no libp2p-quic binding for ${platform}-${arch}`)
}

export const quicBinding: BunPlugin = {
  name: 'libp2p-quic static binding',
  setup(build) {
    build.onLoad({ filter: /@chainsafe[\\/]libp2p-quic[\\/]dist[\\/]src[\\/]napi\.js$/ }, async () => {
      const pkg = bindingPackage()
      const { readdirSync } = await import('node:fs')
      const dir = require.resolve(`${pkg}/package.json`).replace(/package\.json$/, '')
      const file = readdirSync(dir).find((f) => f.endsWith('.node'))
      if (!file) throw new Error(`${pkg} has no .node file`)
      return {
        loader: 'js',
        contents: `const binding = require(${JSON.stringify(`${pkg}/${file}`)})\nexport const { ${EXPORTS.join(', ')} } = binding\n`,
      }
    })
  },
}
